stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  script:
    - npm ci
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .next/cache/
      - node_modules/
  artifacts:
    paths:
      - .next/
      - node_modules/
    expire_in: 1h

# Test Stage
test:
  stage: test
  dependencies:
    - build
  script:
    # Start the built Next.js app in the background
    - npm run start &

    # Wait until it's responding before running Cypress
    - npx wait-on http://localhost:3000

    # Run Cypress against the running app
    - npx cypress run

# Deploy Stage
deploy:
  stage: deploy
  script:
    # Stop and remove the existing container if it exists
    - if (docker ps -a --filter "name=discocord_fe" | Select-String "discocord_fe") { docker rm -f discocord_fe }

    # Remove the old image if it exists
    - if (docker images -q discocord_fe) { docker rmi discocord_fe }

    # Build the Docker image
    - docker build -t discocord_fe .

    # Run the new container
    - docker run -d -p 3300:3000 --name discocord_fe discocord_fe
