stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
    - node_modules/
    - .next/

# Test Stage
test:
  stage: test
  image: cypress/browsers
  script:
    - npm ci
    - npx cypress run --browser chrome 

# Deploy Stage
deploy:
  stage: deploy
  script:
    - if (docker ps -a --filter "name=discocord_fe" | Select-String "discocord_fe") { docker rm -f discocord_fe }
    - if (docker images -q discocord_fe) { docker rmi discocord_fe }
    
    - docker build --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$env:NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY --build-arg CLERK_SECRET_KEY=$env:CLERK_SECRET_KEY -t discocord_fe .

    - docker run -d -p 3300:3000 --name discocord_fe -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$env:NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY -e CLERK_SECRET_KEY=$env:CLERK_SECRET_KEY discocord_fe

    # Run container with env vars
   