import { type Metadata } from 'next'
import { ClerkProvider, SignedIn, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#23272A]`}> {/* base dark bg behind hero */}
          {/* Show user button only when authenticated; remove header gap for signed out users */}
          <SignedIn>
            <div className="fixed top-2 right-2 z-50 flex items-center gap-3 p-2 rounded-full bg-black/30 backdrop-blur-sm shadow-sm">
              {/* afterSignOutUrl deprecated: use signOut callback in a custom button if custom redirect needed */}
              <UserButton />
            </div>
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}